toma_lecturas/lecturas/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('index/', views.layout, name='layout'), 
    path('logout/',views.exit,name='exit'),
    path('', views.custom_login, name='login'),
    path('Barrio/indexbarrio',views.indexbarrio,name='indexbarrio'),
    path('Barrio/crearbarrio',views.crearbarrio,name="crearbarrio"),
    path('Barrio/editarbarrio/<int:id>/',views.editarbarrio,name="editarbarrio"),
    path('Barrio/eliminarbarrio/<int:id>/', views.eliminarbarrio, name="eliminarbarrio"),


    path('Micromedidor/indexmicromedidor',views.indexmicromedidor,name='indexmicromedidor'),
    path('Micromedidor/crearmicromedidor',views.crearmicromedidor,name="crearmicromedidor"),
    path('Micromedidor/editarmicromedidor/<int:id>/',views.editarmicromedidor,name="editarmicromedidor"),
    path('Micromedidor/eliminarmicromedidor/<int:id>/',views.eliminarmicromedidor,name="eliminarmicromedidor"),

    
    path('Suscriptor/indexsucriptor',views.indexsuscriptor,name='indexsuscriptor'),
    path('Suscriptor/crearsuscriptor',views.crearsuscriptor,name="crearsuscriptor"),
    path('Suscriptor/editarsuscriptor/<int:id>/',views.editarsuscriptor,name="editarsuscriptor"),
    path('Suscriptor/eliminarsuscriptor/<int:id>/',views.eliminarsuscriptor,name="eliminarsuscriptor"),
    ##para detalles suscriptor##
    path('detalles_suscriptor/<int:id>/', views.detalles_suscriptor, name='detallessuscriptor'),


    path('SuscriptorMicromedidor/indexsuscriptorMicromedidor',views.indexsuscriptormicromedidor,name='indexsuscriptorMicromedidor') ,
    path('SuscriptorMicromedidor/crearsuscriptormicromedidor',views.crearsuscriptormicromedidor,name="crearsuscriptormicromedidor"),
    path('SuscriptorMicromedidor/editarsuscriptormicromedidor/<int:id>/',views.editarsuscriptormicromedidor,name="editarsuscriptormicromedidor"),
    path('SuscriptorMicromedidor/eliminarsuscriptormicromedidor/<int:id>/',views.eliminarsuscriptormicromedidor,name="eliminarsuscriptormicromedidor"),

    path('Lectura/indexlectura',views.indexlectura,name='indexlectura'),
    path('Lectura/crearlectura',views.crearlectura,name="crearlectura"),
    path('Lectura/editarlectura/<int:id>/',views.editarlectura,name="editarlectura"),
    path('Lectura/eliminarlectura/<int:id>/',views.eliminarlectura,name="eliminarlectura"), 

    ###############detalle de lectura######
    path('lectura/detalle/<int:id>/', views.detalle_lectura, name='detallelectura'),

    path('api/lectura-anterior/<int:suscriptor_id>/', views.obtener_lectura_anterior_api, name='obtener_lectura_anterior_api'),
    
    path('informe/informe', views.verinforme, name='informe'), 
     path('Lectura/descargar/', views.descargar_csv, name='descargar_csv'),
     path('informe/historial_lecturas', views.historial_lecturas, name='historial_lecturas'),
    # path('api/micromedidores/<int:suscriptor_id>/', views.micromedidores_por_suscriptor, name='micromedidores_por_suscriptor'),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 
   

toma_lecturas/toma_lecturas/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lecturas.urls')), 
    
] 

toma_lecturas/lecturas/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver 

class Barrio(models.Model):
    barrio = models.CharField(max_length=20, verbose_name='Nombre del Barrio')
     # Opciones para el campo 'zona'
    OPCIONES_zona= [
        ('zona1', 'Norte'),
        ('zona2', 'Sur occidente'),
        ('zona3', 'En expansion'), 
        
        # Añade más opciones según sea necesario 
    ]

    zona = models.CharField(
        max_length=50,
        choices=OPCIONES_zona,
        verbose_name='zona  ', 
        null=True
    )

    class Meta:
        verbose_name = 'Barrio'
        verbose_name_plural = 'Barrios'

 #eliminar modelo usuario, utilzar clase users de django 

   

class Suscriptor(models.Model):
    primer_nombre = models.CharField(max_length=50,verbose_name='Primer Nombre')
    segundo_nombre = models.CharField(max_length=59,blank=True, verbose_name='Segundo Nombre')
    primer_apellido = models.CharField(max_length=50, verbose_name='Primer Apellido')
    segundo_apellido = models.CharField(max_length=50, blank=True,verbose_name='Segundo Apellido')
    barrio = models.ForeignKey(Barrio, on_delete=models.CASCADE, verbose_name='Barrio')
    direccion_IMAGEN = models.ImageField(upload_to='imagenes/', verbose_name='Dirección Imagen')
      # Opciones para el campo 'estrato_socioeconomico'
    OPCIONES_Estrato_social= [
        ('Estrato1', 'Bajo Bajo'),
        ('Estrato2', 'Bajo'),
        ('Estrato3', 'Medio Bajo'), 
        ('Estrato4', 'Medio '), 
        
        # Añade más opciones según sea necesario 
    ]

    Estrato_socioeconomico = models.CharField(
        max_length=50,
        choices=OPCIONES_Estrato_social,
        verbose_name='estrato socioeconimico  ', 
        null=True
    )
     # Opciones para el campo 'uso'
    OPCIONES_Uso= [
        ('Uso1', 'Comercial'),
        ('Uso2', 'Residencial'),
        ('Uso3', 'Oficial'), 
        
        
        # Añade más opciones según sea necesario 
    ]

    Uso = models.CharField(
        max_length=50,
        choices=OPCIONES_Uso,
        verbose_name='Uso  ', 
        null=True
    )

    class Meta:
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'

class Micromedidor(models.Model):
    nuid = models.CharField(max_length=20, verbose_name='NUID',unique=True) #dejar como unico 
    medidor = models.CharField(max_length=20, verbose_name='Medidor')
    fecha_instalacion = models.DateField(verbose_name='Fecha de Instalación') 
   


    class Meta:
        verbose_name = 'Micromedidor'
        verbose_name_plural = 'Micromedidores'

  

class SuscriptorMicromedidor(models.Model):
    suscriptor = models.ForeignKey(Suscriptor, on_delete=models.CASCADE, verbose_name='Suscriptor')
    micromedidor = models.ForeignKey(Micromedidor, on_delete=models.CASCADE, verbose_name='Micromedidor')

    class Meta:
        verbose_name = 'Relación Suscriptor-Micromedidor'
        verbose_name_plural = 'Relaciones Suscriptor-Micromedidor'



    
class Lectura(models.Model):
    suscriptor_micromedidor = models.ForeignKey(SuscriptorMicromedidor, on_delete=models.CASCADE, verbose_name='Relación Suscriptor-Micromedidor')
    mes_anterior = models.CharField(verbose_name='Mes anterior', max_length=50, blank=True, null=True)
    mes_actual = models.CharField(verbose_name='Mes actual', max_length=50, blank=True, null=True)
    lectura_anterior = models.IntegerField(verbose_name='Lectura anterior', default=0) 
    lectura_actual = models.IntegerField(verbose_name='Lectura actual', default=0) 
    FechaLectura = models.DateTimeField(verbose_name='Fecha de Lectura', auto_now_add=True, editable=False)
    Observaciones = models.CharField(max_length=100, verbose_name='Observaciones', blank=True, null=True)
    OPCIONES_Tipo_lectura = [
        ('tipo1', 'Lectura'),
        ('tipo2', 'Promedio'),
    ]

    tipo_lectura = models.CharField(
        max_length=50,
        choices=OPCIONES_Tipo_lectura,
        verbose_name='Tipo de lectura', 
        null=True
    )
    OPCIONES_estado_micromedidor = [
        ('estado1', 'Bueno'),
        ('estado2', 'Malo'),
    ]

    estado_micromedidor = models.CharField(
        max_length=50,
        choices=OPCIONES_estado_micromedidor,
        verbose_name='Estado del micromedidor',
        null=True
    )
    consumototal = models.IntegerField(verbose_name='Consumo total', default=0) 

    class Meta:
        verbose_name = 'Lectura'
        verbose_name_plural = 'Lecturas'

    def calcular_consumo_total(self):
        if self.lectura_anterior is not None and self.lectura_actual is not None:
            return self.lectura_actual - self.lectura_anterior
        return 0
    
def save(self, *args, **kwargs):
        self.consumototal = self.calcular_consumo_total()
        super(Lectura, self).save(*args, **kwargs)    

@receiver(post_save, sender=Lectura)
def actualizar_lectura_anterior(sender, instance, created, **kwargs):
    if created:
        # Obtener la última lectura anterior para el mismo suscriptor y micromedidor
        lectura_anterior = Lectura.objects.filter(
            suscriptor_micromedidor=instance.suscriptor_micromedidor
        ).exclude(id=instance.id).order_by('-FechaLectura').first()

        if lectura_anterior:
            instance.mes_anterior = lectura_anterior.mes_actual
            instance.lectura_anterior = lectura_anterior.lectura_actual
            instance.save() 

toma_lecturas/lecturas/forms.py
from django import forms
from .models import Barrio, Suscriptor, Micromedidor, SuscriptorMicromedidor, Lectura
#####################################################3
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class BarrioForm(forms.ModelForm):
    class Meta:
        model = Barrio
        fields = ['barrio', 'zona']

    def __init__(self, *args, **kwargs):
        super(BarrioForm, self).__init__(*args, **kwargs)

        # Opciones para el campo 'zona'
        self.fields['zona'].widget.choices = Barrio.OPCIONES_zona 




class SuscriptorForm(forms.ModelForm):
    class Meta:
        model = Suscriptor
        fields = ['primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido', 'barrio', 'direccion_IMAGEN', 'Estrato_socioeconomico', 'Uso']

    def __init__(self, *args, **kwargs):
        super(SuscriptorForm, self).__init__(*args, **kwargs)
        self.fields['Estrato_socioeconomico'].widget.choices = Suscriptor.OPCIONES_Estrato_social
        self.fields['Uso'].widget.choices = Suscriptor.OPCIONES_Uso

        # Filtrar los barrios disponibles para seleccionar en el formulario
        self.fields['barrio'].queryset = Barrio.objects.all()  # Puedes ajustar este queryset según tu lógica de negocio


class MicromedidorForm(forms.ModelForm):
    class Meta:
        model = Micromedidor
        fields = ['nuid', 'medidor', 'fecha_instalacion'] 

    def clean_nuid(self):
        # Obtener el valor ingresado en el campo nuid
        nuid = self.cleaned_data.get('nuid')
        
        # Verificar si ya existe un Micromedidor con este nuid en la base de datos
        if Micromedidor.objects.filter(nuid=nuid).exists():
            # Obtener la instancia actual del micromedidor (si existe)
            instance = getattr(self, 'instance', None)
            if instance and instance.id:
                # Si la instancia existe y tiene un ID, significa que se está editando
                # En ese caso, excluimos este micromedidor de la verificación de duplicados
                if Micromedidor.objects.exclude(id=instance.id).filter(nuid=nuid).exists():
                    raise forms.ValidationError("El NUID ingresado ya está en uso. Por favor, ingrese un valor único.")
            else:
                raise forms.ValidationError("El NUID ingresado ya está en uso. Por favor, ingrese un valor único.")
        
        return nuid 
    

    #verificar si existe un micromedidor en la base de datos
    def clean_medidor(self):
        medidor = self.cleaned_data.get('medidor')
        if Micromedidor.objects.filter(medidor=medidor).exists():
            instance= getattr(self, 'instance',None)
            if instance and instance.id:
               if Micromedidor.objects.exclude(id=instance.id).filter(medidor=medidor).exists():
                raise forms.ValidationError("El medidor ingresado ya está asociado a otro micromedidor. Por favor, ingrese un medidor válido.")
            else:
                raise forms.ValidationError("el valor que ingresaste para medidor ya existe, por favor cambiarlo")
        return medidor 
        


class SuscriptorMicromedidorForm(forms.ModelForm):
    class Meta:
        model = SuscriptorMicromedidor
        fields = ['suscriptor', 'micromedidor'] 
    def __init__(self, *args, **kwargs):
        super(SuscriptorMicromedidorForm, self).__init__(*args, **kwargs)
        self.fields['suscriptor'].queryset = Suscriptor.objects.all()
        self.fields['micromedidor'].queryset = Micromedidor.objects.all() 

    def clean(self):
        cleaned_data = super().clean()
        #suscriptor = cleaned_data.get('suscriptor')
        micromedidor = cleaned_data.get('micromedidor')
        instance = getattr(self, 'instance', None)

        # Verificar que el micromedidor no esté asociado a otro suscriptor
        if SuscriptorMicromedidor.objects.filter(micromedidor=micromedidor).exclude(id=instance.id).exists():
            raise forms.ValidationError('Este micromedidor ya está asociado a otro suscriptor.')

        return cleaned_data


class LecturaForm(forms.ModelForm):
    class Meta:
        model = Lectura
        fields = ['suscriptor_micromedidor', 'lectura_actual','mes_actual','mes_anterior', 'Observaciones', 'tipo_lectura', 'estado_micromedidor'] 

    def __init__(self, *args, **kwargs):
        super(LecturaForm, self).__init__(*args, **kwargs)
        self.fields['tipo_lectura'].widget.choices = Lectura.OPCIONES_Tipo_lectura
        self.fields['estado_micromedidor'].widget.choices = Lectura.OPCIONES_estado_micromedidor
        self.fields['suscriptor_micromedidor'].queryset = SuscriptorMicromedidor.objects.all() 

    def clean_lectura_actual(self):
        lectura_actual = self.cleaned_data['lectura_actual']
        return lectura_actual 
    def clean(self):
        cleaned_data = super().clean()
        suscriptor_micromedidor = cleaned_data.get('suscriptor_micromedidor')

        if not suscriptor_micromedidor:
            raise forms.ValidationError("Suscriptor Micromedidor no encontrado. Por favor, seleccione uno válido.")

        return cleaned_data
        
class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

toma_lecturas/lecturas/templates/Lectura/crear.html
{% extends 'layout.html' %}
{% block titulo %} CREAR LECTURA {% endblock %}
{% block section %}
<style>
    input[readonly] {
    background-color: #e9ecef;
    color: #495057;
    cursor: not-allowed;
}
</style>
<div class="form-container">
    <div class="form-background">
        <div class="card text-start">
            <div class="card-body">
                <h4 class="card-title font-weight-bold">Registrar lectura</h4>
                {% if error_message %}
                    <div class="alert alert-danger">{{ error_message }}</div>
                {% endif %}
                <div class="mb-3">
                    <form enctype="multipart/form-data" method="post" id="lecturaForm">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="form-label font-weight-bold">Suscriptor Micromedidor:</label>
                            <input type="text" id="suscriptor_search" class="form-control" placeholder="Buscar suscriptor micromedidor..." oninput="filtrarSuscriptores()">
                            <div class="dropdown" style="position: relative;">
                                <select name="suscriptor_micromedidor" class="form-control mt-2" id="id_suscriptor_micromedidor" size="5" style="display: none;">
                                    {% for suscriptor_micromedidor in suscriptores_micromedidores %}
                                    <option value="{{ suscriptor_micromedidor.id }}"> {{suscriptor_micromedidor.micromedidor.medidor}} </option>
                                    {% endfor %}
                                </select>
                                <div id="suscriptor_dropdown" class="dropdown-menu" style="width: 100%; max-height: 200px; overflow-y: auto;">
                                    {% for suscriptor_micromedidor in suscriptores_micromedidores %}
                                        <div class="dropdown-item" data-value="{{ suscriptor_micromedidor.id }}">{{ suscriptor_micromedidor.suscriptor.primer_nombre }} {{ suscriptor_micromedidor.suscriptor.segundo_nombre }} {{ suscriptor_micromedidor.suscriptor.primer_apellido }} {{ suscriptor_micromedidor.micromedidor.medidor }}</div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>

                        <div class="row mb-2">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="form-label font-weight-bold">Lectura Actual:</label>
                                    <input type="number" name="lectura_actual" class="form-control" id="id_lectura_actual" required>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="form-label font-weight-bold">Lectura Anterior:</label>
                                    <input type="number" name="lectura_anterior" class="form-control" id="id_lectura_anterior" readonly >
                                </div>
                            </div>
                        </div>

                        <div class="mb-3">
                            <label class="form-label font-weight-bold">Consumo Total:</label>
                            <input type="number" name="consumototal" class="form-control" id="id_consumototal" readonly>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="form-label font-weight-bold">Tipo de Lectura:</label>
                                    <select name="tipo_lectura" class="form-control">
                                        {% for tipo, label in form.tipo_lectura.field.choices %}
                                            <option value="{{ tipo }}">{{ label }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="form-label font-weight-bold">Estado del Micromedidor:</label>
                                    <select name="estado_micromedidor" class="form-control">
                                        {% for estado, label in form.estado_micromedidor.field.choices %}
                                            <option value="{{ estado }}">{{ label }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="form-label font-weight-bold">Mes Anterior:</label>
                                    <input type="text" name="mes_anterior" class="form-control" readonly>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="form-label font-weight-bold">Mes Actual:</label>
                                    <input type="text" name="mes_actual" class="form-control" readonly>
                                </div>
                            </div>
                        </div>

                        <div class="mb-3">
                            <label class="form-label font-weight-bold">Fecha de Lectura:</label>
                            <input type="text" name="FechaLectura" class="form-control" id="id_fechalectura" readonly>
                        </div>

                        <div class="mb-3">
                            <label class="form-label font-weight-bold">Observaciones:</label>
                            <textarea name="observaciones" class="form-control"></textarea>
                        </div>

                        <div class="mb-3">
                            <button type="button" class="btn btn-primary" onclick="calcularConsumoTotal()">Calcular Consumo Total</button>
                            <button type="submit" class="btn btn-primary" id="submitBtn">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var now = new Date();
        var year = now.getFullYear();
        var month = ('0' + (now.getMonth() + 1)).slice(-2);
        var day = ('0' + now.getDate()).slice(-2);
        var hours = ('0' + now.getHours()).slice(-2); 
        var minutes = ('0' + now.getMinutes()).slice(-2);

        var formattedDateTime = `${year}-${month}-${day}T${hours}:${minutes}`;
        document.getElementById('id_fechalectura').value = formattedDateTime;

        var monthNames = [
            'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
            'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
        ];
        var monthIndex = now.getMonth();
        var previousMonth = monthIndex === 0 ? 11 : monthIndex - 1;

        document.querySelector('input[name="mes_actual"]').value = monthNames[monthIndex];
        document.querySelector('input[name="mes_anterior"]').value = monthNames[previousMonth];
    });

    function calcularConsumoTotal() {
        var lecturaActual = parseInt(document.getElementById('id_lectura_actual').value);
        var lecturaAnterior = parseInt(document.getElementById('id_lectura_anterior').value);

        if (!isNaN(lecturaActual) && !isNaN(lecturaAnterior)) {
            var consumoTotal = lecturaActual - lecturaAnterior;
            document.getElementById('id_consumototal').value = consumoTotal;
        }
    }

    document.getElementById('lecturaForm').addEventListener('submit', function(event) {
        var consumoTotal = parseInt(document.getElementById('id_consumototal').value);
        if (consumoTotal < 0) {
            event.preventDefault();
            alert('El consumo total no puede ser negativo. Por favor, revisa los valores ingresados.');
        }
    });

    function filtrarSuscriptores() {
        var filter = document.getElementById('suscriptor_search').value.toLowerCase();
        var dropdown = document.getElementById('suscriptor_dropdown');
        var items = dropdown.getElementsByClassName('dropdown-item');

        for (var i = 0; i < items.length; i++) {
            var item = items[i];
            var text = item.textContent.toLowerCase();

            if (text.indexOf(filter) > -1) {
                item.style.display = '';
            } else {
                item.style.display = 'none';
            }
        }
    }

    document.getElementById('suscriptor_dropdown').addEventListener('click', function(event) {
        if (event.target && event.target.matches('.dropdown-item')) {
            var selectedValue = event.target.getAttribute('data-value');
            var select = document.getElementById('id_suscriptor_micromedidor');
            var options = select.options;

            for (var i = 0; i < options.length; i++) {
                if (options[i].value == selectedValue) {
                    options[i].selected = true;
                    break;
                }
            }

            document.getElementById('suscriptor_search').value = event.target.textContent;
            event.target.parentNode.style.display = 'none'; // Hide dropdown after selection
        }
    });

    document.getElementById('suscriptor_search').addEventListener('focus', function() {
        document.getElementById('suscriptor_dropdown').style.display = 'block'; // Show dropdown on focus
    });

    document.addEventListener('click', function(event) {
        var isClickInside = document.getElementById('suscriptor_search').contains(event.target) || document.getElementById('suscriptor_dropdown').contains(event.target);
        if (!isClickInside) {
            document.getElementById('suscriptor_dropdown').style.display = 'none'; // Hide dropdown if clicked outside
        }
    });
</script>
{% endblock %}

toma_lecturas/lecturas/templates/Lectura/detalle.html
{% extends 'layout.html' %}
{% block titulo %} DETALLE DE LECTURA {% endblock %}
{% block section %}
<div class="form-container">
    <div class="form-background">
        <div class="card text-start">
            <div class="card-body">
                <h4 class="card-title">Detalle de Lectura</h4>
                
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label class="form-label font-weight-bold">Suscriptor</label>
                        <input type="text" class="form-control" value="{{ lectura.suscriptor_micromedidor.suscriptor.primer_nombre }} {{ lectura.suscriptor_micromedidor.suscriptor.segundo_nombre }} {{ lectura.suscriptor_micromedidor.suscriptor.primer_apellido }} {{ lectura.suscriptor_micromedidor.suscriptor.segundo_apellido }}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label font-weight-bold">Micromedidor</label>
                        <input type="text" class="form-control" value="{{ lectura.suscriptor_micromedidor.micromedidor.medidor }}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label font-weight-bold">Mes Anterior</label>
                        <input type="text" class="form-control" value="{{ lectura.mes_anterior }}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label font-weight-bold">Mes Actual</label>
                        <input type="text" class="form-control" value="{{ lectura.mes_actual }}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label font-weight-bold">Lectura Anterior</label>
                        <input type="text" class="form-control" value="{{ lectura.lectura_anterior }}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label font-weight-bold">Lectura Actual</label>
                        <input type="text" class="form-control" value="{{ lectura.lectura_actual }}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label font-weight-bold">Consumo Total</label>
                        <input type="text" class="form-control" value="{{ lectura.consumototal }}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label font-weight-bold">Fecha de Lectura</label>
                        <input type="text" class="form-control" value="{{ lectura.FechaLectura }}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label font-weight-bold">Observaciones</label>
                        <input type="text" class="form-control" value="{{ lectura.Observaciones }}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label font-weight-bold">Tipo de Lectura</label>
                        <input type="text" class="form-control" value="{{ lectura.get_tipo_lectura_display }}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label font-weight-bold">Estado del Micromedidor</label>
                        <input type="text" class="form-control" value="{{ lectura.get_estado_micromedidor_display }}" readonly>
                    </div>
                </div>

                <a class="btn btn-secondary" href="{% url 'indexlectura' %}" role="button">Volver</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

toma_lecturas/lecturas/templates/Lectura/eliminar.html
{% extends 'layout.html' %} {% block titulo %} ELIMINAR SUSCRIPTOR DE MICROMEDIDOR {% endblock %} {% block section %}
<div class="card text-start">
    <div class="card-body">
        <p class="card-text">
            <h4>¿Estás seguro de que deseas eliminar este suscriptor asociado a este micromedidor?</h4> 
            <p>{{ barrio.barrio }}</p>

            <form method="post" action="{% url 'eliminarlectura' lectura.id %}"> 
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a href="{% url 'indexlectura' %}" class="btn btn-secondary">Cancelar</a> 
            </form>
        </p>
    </div>
</div>
{% endblock %} 

toma_lecturas/lecturas/templates/Lectura/form.html
<!-- lectura_form.html -->
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="mb-3">
        <label class="form-check-label">{{ field.label }} </label>
        {% if field.name in ['suscriptor_micromedidor', 'tipo_lectura', 'estado_micromedidor', 'Mes_lectura'] %}
        <select name="{{ field.name }}" class="form-control">
            {% for value, label in field.field.choices %}
            <option value="{{ value }}">{{ label }}</option>
            {% endfor %}
        </select>
        {% else %}
        {{ field }}
        {% endif %}
        <div class="col-12 help-text">{{ field.errors }}</div>
    </div>
    {% endfor %}
    <input name="" id="" class="btn btn-primary" type="submit" value="Guardar">
</form>