toma_lecturas/lecturas/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('index/', views.layout, name='layout'), 
    path('logout/',views.exit,name='exit'),
    path('', views.custom_login, name='login'),
    path('Barrio/indexbarrio',views.indexbarrio,name='indexbarrio'),
    path('Barrio/crearbarrio',views.crearbarrio,name="crearbarrio"),
    path('Barrio/editarbarrio/<int:id>/',views.editarbarrio,name="editarbarrio"),
    path('Barrio/eliminarbarrio/<int:id>/', views.eliminarbarrio, name="eliminarbarrio"),


    path('Micromedidor/indexmicromedidor',views.indexmicromedidor,name='indexmicromedidor'),
    path('Micromedidor/crearmicromedidor',views.crearmicromedidor,name="crearmicromedidor"),
    path('Micromedidor/editarmicromedidor/<int:id>/',views.editarmicromedidor,name="editarmicromedidor"),
    path('Micromedidor/eliminarmicromedidor/<int:id>/',views.eliminarmicromedidor,name="eliminarmicromedidor"),

    
    path('Suscriptor/indexsucriptor',views.indexsuscriptor,name='indexsuscriptor'),
    path('Suscriptor/crearsuscriptor',views.crearsuscriptor,name="crearsuscriptor"),
    path('Suscriptor/editarsuscriptor/<int:id>/',views.editarsuscriptor,name="editarsuscriptor"),
    path('Suscriptor/eliminarsuscriptor/<int:id>/',views.eliminarsuscriptor,name="eliminarsuscriptor"),
    ##para detalles suscriptor##
    path('detalles_suscriptor/<int:id>/', views.detalles_suscriptor, name='detallessuscriptor'),


    path('SuscriptorMicromedidor/indexsuscriptorMicromedidor',views.indexsuscriptormicromedidor,name='indexsuscriptorMicromedidor') ,
    path('SuscriptorMicromedidor/crearsuscriptormicromedidor',views.crearsuscriptormicromedidor,name="crearsuscriptormicromedidor"),
    path('SuscriptorMicromedidor/editarsuscriptormicromedidor/<int:id>/',views.editarsuscriptormicromedidor,name="editarsuscriptormicromedidor"),
    path('SuscriptorMicromedidor/eliminarsuscriptormicromedidor/<int:id>/',views.eliminarsuscriptormicromedidor,name="eliminarsuscriptormicromedidor"),

    path('Lectura/indexlectura',views.indexlectura,name='indexlectura'),
    path('Lectura/crearlectura',views.crearlectura,name="crearlectura"),
    path('Lectura/editarlectura/<int:id>/',views.editarlectura,name="editarlectura"),
    path('Lectura/eliminarlectura/<int:id>/',views.eliminarlectura,name="eliminarlectura"), 

    ###############detalle de lectura######
    path('lectura/detalle/<int:id>/', views.detalle_lectura, name='detallelectura'),

    path('api/lectura-anterior/<int:suscriptor_id>/', views.obtener_lectura_anterior_api, name='obtener_lectura_anterior_api'),
    
    path('informe/informe', views.verinforme, name='informe'), 
     path('Lectura/descargar/', views.descargar_csv, name='descargar_csv'),
     path('informe/historial_lecturas', views.historial_lecturas, name='historial_lecturas'),
    # path('api/micromedidores/<int:suscriptor_id>/', views.micromedidores_por_suscriptor, name='micromedidores_por_suscriptor'),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 
   

toma_lecturas/toma_lecturas/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lecturas.urls')), 
    
] 

toma_lecturas/lecturas/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver 

class Barrio(models.Model):
    barrio = models.CharField(max_length=20, verbose_name='Nombre del Barrio')
     # Opciones para el campo 'zona'
    OPCIONES_zona= [
        ('zona1', 'Norte'),
        ('zona2', 'Sur occidente'),
        ('zona3', 'En expansion'), 
        
        # Añade más opciones según sea necesario 
    ]

    zona = models.CharField(
        max_length=50,
        choices=OPCIONES_zona,
        verbose_name='zona  ', 
        null=True
    )

    class Meta:
        verbose_name = 'Barrio'
        verbose_name_plural = 'Barrios'

 #eliminar modelo usuario, utilzar clase users de django 

   

class Suscriptor(models.Model):
    primer_nombre = models.CharField(max_length=50,verbose_name='Primer Nombre')
    segundo_nombre = models.CharField(max_length=59,blank=True, verbose_name='Segundo Nombre')
    primer_apellido = models.CharField(max_length=50, verbose_name='Primer Apellido')
    segundo_apellido = models.CharField(max_length=50, blank=True,verbose_name='Segundo Apellido')
    barrio = models.ForeignKey(Barrio, on_delete=models.CASCADE, verbose_name='Barrio')
    direccion_IMAGEN = models.ImageField(upload_to='imagenes/', verbose_name='Dirección Imagen')
      # Opciones para el campo 'estrato_socioeconomico'
    OPCIONES_Estrato_social= [
        ('Estrato1', 'Bajo Bajo'),
        ('Estrato2', 'Bajo'),
        ('Estrato3', 'Medio Bajo'), 
        ('Estrato4', 'Medio '), 
        
        # Añade más opciones según sea necesario 
    ]

    Estrato_socioeconomico = models.CharField(
        max_length=50,
        choices=OPCIONES_Estrato_social,
        verbose_name='estrato socioeconimico  ', 
        null=True
    )
     # Opciones para el campo 'uso'
    OPCIONES_Uso= [
        ('Uso1', 'Comercial'),
        ('Uso2', 'Residencial'),
        ('Uso3', 'Oficial'), 
        
        
        # Añade más opciones según sea necesario 
    ]

    Uso = models.CharField(
        max_length=50,
        choices=OPCIONES_Uso,
        verbose_name='Uso  ', 
        null=True
    )

    class Meta:
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'

class Micromedidor(models.Model):
    nuid = models.CharField(max_length=20, verbose_name='NUID',unique=True) #dejar como unico 
    medidor = models.CharField(max_length=20, verbose_name='Medidor')
    fecha_instalacion = models.DateField(verbose_name='Fecha de Instalación') 
   


    class Meta:
        verbose_name = 'Micromedidor'
        verbose_name_plural = 'Micromedidores'

  

class SuscriptorMicromedidor(models.Model):
    suscriptor = models.ForeignKey(Suscriptor, on_delete=models.CASCADE, verbose_name='Suscriptor')
    micromedidor = models.ForeignKey(Micromedidor, on_delete=models.CASCADE, verbose_name='Micromedidor')

    class Meta:
        verbose_name = 'Relación Suscriptor-Micromedidor'
        verbose_name_plural = 'Relaciones Suscriptor-Micromedidor'



    
class Lectura(models.Model):
    suscriptor_micromedidor = models.ForeignKey(SuscriptorMicromedidor, on_delete=models.CASCADE, verbose_name='Relación Suscriptor-Micromedidor')
    mes_anterior = models.CharField(verbose_name='Mes anterior', max_length=50, blank=True, null=True)
    mes_actual = models.CharField(verbose_name='Mes actual', max_length=50, blank=True, null=True)
    lectura_anterior = models.IntegerField(verbose_name='Lectura anterior', default=0) 
    lectura_actual = models.IntegerField(verbose_name='Lectura actual', default=0) 
    FechaLectura = models.DateTimeField(verbose_name='Fecha de Lectura', auto_now_add=True, editable=False)
    Observaciones = models.CharField(max_length=100, verbose_name='Observaciones', blank=True, null=True)
    OPCIONES_Tipo_lectura = [
        ('tipo1', 'Lectura'),
        ('tipo2', 'Promedio'),
    ]

    tipo_lectura = models.CharField(
        max_length=50,
        choices=OPCIONES_Tipo_lectura,
        verbose_name='Tipo de lectura', 
        null=True
    )
    OPCIONES_estado_micromedidor = [
        ('estado1', 'Bueno'),
        ('estado2', 'Malo'),
    ]

    estado_micromedidor = models.CharField(
        max_length=50,
        choices=OPCIONES_estado_micromedidor,
        verbose_name='Estado del micromedidor',
        null=True
    )
    consumototal = models.IntegerField(verbose_name='Consumo total', default=0) 

    class Meta:
        verbose_name = 'Lectura'
        verbose_name_plural = 'Lecturas'

    def calcular_consumo_total(self):
        if self.lectura_anterior is not None and self.lectura_actual is not None:
            return self.lectura_actual - self.lectura_anterior
        return 0
    
def save(self, *args, **kwargs):
        self.consumototal = self.calcular_consumo_total()
        super(Lectura, self).save(*args, **kwargs)    

@receiver(post_save, sender=Lectura)
def actualizar_lectura_anterior(sender, instance, created, **kwargs):
    if created:
        # Obtener la última lectura anterior para el mismo suscriptor y micromedidor
        lectura_anterior = Lectura.objects.filter(
            suscriptor_micromedidor=instance.suscriptor_micromedidor
        ).exclude(id=instance.id).order_by('-FechaLectura').first()

        if lectura_anterior:
            instance.mes_anterior = lectura_anterior.mes_actual
            instance.lectura_anterior = lectura_anterior.lectura_actual
            instance.save() 

toma_lecturas/lecturas/forms.py
from django import forms
from .models import Barrio, Suscriptor, Micromedidor, SuscriptorMicromedidor, Lectura
#####################################################3
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class BarrioForm(forms.ModelForm):
    class Meta:
        model = Barrio
        fields = ['barrio', 'zona']

    def __init__(self, *args, **kwargs):
        super(BarrioForm, self).__init__(*args, **kwargs)

        # Opciones para el campo 'zona'
        self.fields['zona'].widget.choices = Barrio.OPCIONES_zona 




class SuscriptorForm(forms.ModelForm):
    class Meta:
        model = Suscriptor
        fields = ['primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido', 'barrio', 'direccion_IMAGEN', 'Estrato_socioeconomico', 'Uso']

    def __init__(self, *args, **kwargs):
        super(SuscriptorForm, self).__init__(*args, **kwargs)
        self.fields['Estrato_socioeconomico'].widget.choices = Suscriptor.OPCIONES_Estrato_social
        self.fields['Uso'].widget.choices = Suscriptor.OPCIONES_Uso

        # Filtrar los barrios disponibles para seleccionar en el formulario
        self.fields['barrio'].queryset = Barrio.objects.all()  # Puedes ajustar este queryset según tu lógica de negocio


class MicromedidorForm(forms.ModelForm):
    class Meta:
        model = Micromedidor
        fields = ['nuid', 'medidor', 'fecha_instalacion'] 

    def clean_nuid(self):
        # Obtener el valor ingresado en el campo nuid
        nuid = self.cleaned_data.get('nuid')
        
        # Verificar si ya existe un Micromedidor con este nuid en la base de datos
        if Micromedidor.objects.filter(nuid=nuid).exists():
            # Obtener la instancia actual del micromedidor (si existe)
            instance = getattr(self, 'instance', None)
            if instance and instance.id:
                # Si la instancia existe y tiene un ID, significa que se está editando
                # En ese caso, excluimos este micromedidor de la verificación de duplicados
                if Micromedidor.objects.exclude(id=instance.id).filter(nuid=nuid).exists():
                    raise forms.ValidationError("El NUID ingresado ya está en uso. Por favor, ingrese un valor único.")
            else:
                raise forms.ValidationError("El NUID ingresado ya está en uso. Por favor, ingrese un valor único.")
        
        return nuid 
    

    #verificar si existe un micromedidor en la base de datos
    def clean_medidor(self):
        medidor = self.cleaned_data.get('medidor')
        if Micromedidor.objects.filter(medidor=medidor).exists():
            instance= getattr(self, 'instance',None)
            if instance and instance.id:
               if Micromedidor.objects.exclude(id=instance.id).filter(medidor=medidor).exists():
                raise forms.ValidationError("El medidor ingresado ya está asociado a otro micromedidor. Por favor, ingrese un medidor válido.")
            else:
                raise forms.ValidationError("el valor que ingresaste para medidor ya existe, por favor cambiarlo")
        return medidor 
        


class SuscriptorMicromedidorForm(forms.ModelForm):
    class Meta:
        model = SuscriptorMicromedidor
        fields = ['suscriptor', 'micromedidor'] 
    def __init__(self, *args, **kwargs):
        super(SuscriptorMicromedidorForm, self).__init__(*args, **kwargs)
        self.fields['suscriptor'].queryset = Suscriptor.objects.all()
        self.fields['micromedidor'].queryset = Micromedidor.objects.all() 

    def clean(self):
        cleaned_data = super().clean()
        #suscriptor = cleaned_data.get('suscriptor')
        micromedidor = cleaned_data.get('micromedidor')
        instance = getattr(self, 'instance', None)

        # Verificar que el micromedidor no esté asociado a otro suscriptor
        if SuscriptorMicromedidor.objects.filter(micromedidor=micromedidor).exclude(id=instance.id).exists():
            raise forms.ValidationError('Este micromedidor ya está asociado a otro suscriptor.')

        return cleaned_data


class LecturaForm(forms.ModelForm):
    class Meta:
        model = Lectura
        fields = ['suscriptor_micromedidor', 'lectura_actual','mes_actual','mes_anterior', 'Observaciones', 'tipo_lectura', 'estado_micromedidor'] 

    def __init__(self, *args, **kwargs):
        super(LecturaForm, self).__init__(*args, **kwargs)
        self.fields['tipo_lectura'].widget.choices = Lectura.OPCIONES_Tipo_lectura
        self.fields['estado_micromedidor'].widget.choices = Lectura.OPCIONES_estado_micromedidor
        self.fields['suscriptor_micromedidor'].queryset = SuscriptorMicromedidor.objects.all() 

    def clean_lectura_actual(self):
        lectura_actual = self.cleaned_data['lectura_actual']
        return lectura_actual 
    def clean(self):
        cleaned_data = super().clean()
        suscriptor_micromedidor = cleaned_data.get('suscriptor_micromedidor')

        if not suscriptor_micromedidor:
            raise forms.ValidationError("Suscriptor Micromedidor no encontrado. Por favor, seleccione uno válido.")

        return cleaned_data
        
class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

toma_lecturas/lecturas/templates/Suscriptor/crear.html
{% extends 'layout.html' %}

{% block titulo %}
CREAR SUSCRIPTOR
{% endblock %}


{% block section %}
<div class="form-container">
 <div class="form-background">
  <div class="card text-start">
    <div class="card-body">
        <h4 class="card-title font-weight-bold">Inscribir  Suscriptor</h4>
        <p class="card-text">
            <form enctype="multipart/form-data" method="post">
              {% csrf_token %}
              <fieldset>
                <div class="row mb-2">
                  <div class="form-group col-md-6">
                    <label class="form-label font-weight-bold">Primer Nombre </label> 
                    <input type="text" name="primer_nombre" class="form-control" id="id_primer_nombre" required>
                  </div>
                  
                 <!-- Segundo nombre -->
                  <div class="form-group col-md-6">
                    <label class="form-label font-weight-bold" >Segundo nombre</label>  
                    <input type="text" name="segundo_nombre" class="form-control" id="id_segundo_nombre" >
                  </div>
                
                </div>
                
               
            
               <div class="row mb-2">
                 <!-- Primer apellido -->
                  <div class="form-group col-md-6">
                    <label class="form-label font-weight-bold" >Primer apellido</label>  
                    <input type="text" name="primer_apellido" class="form-control" id="id_primer_apellido" required>
                   
                  </div>
                 
                
                 <!-- Segundo apellido -->
                  <div class="form-group col-md-6">
                    <label class="form-label font-weight-bold" >Segundo apellido</label>  
                    <input type="text" name="segundo_apellido" class="form-control" id="id_segundo_apellido" >
                  </div>
               </div>

                <div class="form-group col-md-6">
                  <label class="form-label font-weight-bold" for="direccion_IMAGEN">Imagen</label>
                  {{ form.direccion_IMAGEN }}
                  <div class="help-text">{{ form.direccion_IMAGEN.errors }}</div>
                  
                </div>
              
                <!-- Barrio -->
                <div class="form-group">
                    <label class="form-label font-weight-bold" for="barrio">Barrio</label>
                    <div class="col-md-4">
                        <select name="{{ form.barrio.name }}" class="form-control">
                            {% for barrio in barrios %}
                            <option value="{{ barrio.pk }}">{{ barrio.barrio }}</option>
                            {% endfor %}
                        </select>
                        <div class="col-12 help-text">{{ form.barrio.errors }}</div>
                    </div>
                </div>

                <!-- Estrato socioeconómico -->
                <div class="form-group">
                    <label class="form-label font-weight-bold" for="Estrato_socioeconomico">Estrato socioeconómico</label>
                    <div class="col-md-4">
                        <select name="{{ form.Estrato_socioeconomico.name }}" class="form-control">
                            {% for value, label in form.Estrato_socioeconomico.field.choices %}
                            <option value="{{ value }}">{{ label }}</option>
                            {% endfor %}
                        </select>
                        <div class="col-12 help-text">{{ form.Estrato_socioeconomico.errors }}</div>
                    </div>
                </div>

                <!-- Uso -->
                <div class="form-group">
                    <label class="form-label font-weight-bold" for="Uso">Uso</label>
                    <div class="col-md-4">
                        <select name="{{ form.Uso.name }}" class="form-control">
                            {% for value, label in form.Uso.field.choices %}
                            <option value="{{ value }}">{{ label }}</option>
                            {% endfor %}
                        </select>
                        <div class="col-12 help-text">{{ form.Uso.errors }}</div>
                    </div>
                </div>

                <input name="" id="" class="btn btn-primary" type="submit" value="Guardar">
              </fieldset>
            </form>
        </p>
    </div>
  </div>
 </div>
</div>
{% endblock %}

toma_lecturas/lecturas/templates/Suscriptor/detalle.html
{% extends 'layout.html' %}
{% block titulo %} Detalles del Suscriptor {% endblock %}
{% block section %}
<div class="form-container">
 <div class="form-background">
   <div class="card text-start">
    <div class="card-body">
        <h4 class="card-title">Detalles del Suscriptor</h4>
        
        <div class="form-row">
            <div class="form-group col-md-6">
                <label class="form-label font-weight-bold">Nombre Completo</label>
                <input type="text" class="form-control" value="{{ suscriptor.primer_nombre }} {{ suscriptor.segundo_nombre }} {{ suscriptor.primer_apellido }} {{ suscriptor.segundo_apellido }}" readonly>
            </div>
            <div class="form-group col-md-6">
                <label class="form-label font-weight-bold">Barrio</label>
                <input type="text" class="form-control" value="{{ suscriptor.barrio.barrio }}" readonly>
            </div>
            <div class="form-group col-md-6">
                <label class="form-label font-weight-bold">Estrato Socioeconómico</label>
                <input type="text" class="form-control" value="{{ suscriptor.get_Estrato_socioeconomico_display }}" readonly>
            </div>
            <div class="form-group col-md-6">
                <label class="form-label font-weight-bold">Uso</label>
                <input type="text" class="form-control" value="{{ suscriptor.get_Uso_display }}" readonly>
            </div>
            <div class="form-group col-md-6">
                <label class="form-label font-weight-bold">Imagen</label>
                <a href="{{ suscriptor.direccion_IMAGEN.url }}" class="form-control-plaintext">{{ suscriptor.direccion_IMAGEN.url }}</a>
            </div>
        </div>
        
        <a class="btn btn-primary" href="{% url 'indexsuscriptor' %}" role="button">Volver a Suscriptores</a>
    </div>
  </div>
 </div>
</div>
{% endblock %}

toma_lecturas/lecturas/templates/Suscriptor/editar.html
{% extends 'layout.html' %}

{% block titulo %}
EDITAR SUSCRIPTOR
{% endblock %}

{% block section %}
<div class="form-container">
    <div class="form-background">
        <div class="card text-start">
            <div class="card-body">
                <h4 class="card-title font-weight-bold">Editar Suscriptor</h4>
                <p class="card-text">
                    <form enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        <fieldset>
                            <div class="row mb-2">
                                <div class="form-group col-md-6">
                                    <label class="form-label font-weight-bold" for="id_primer_nombre">Primer nombre</label>
                                    <input type="text" name="primer_nombre" class="form-control {% if formulario.primer_nombre.errors %}is-invalid{% endif %}" id="id_primer_nombre" value="{{ formulario.primer_nombre.value }}" required>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label font-weight-bold" for="id_segundo_nombre">Segundo nombre</label>
                                    <input type="text" name="segundo_nombre" class="form-control {% if formulario.segundo_nombre.errors %}is-invalid{% endif %}" id="id_segundo_nombre" value="{{ formulario.segundo_nombre.value }}" >
                                </div>
                            </div>
                            <div class="row mb-2">
                                <div class="form-group col-md-6">
                                    <label class="form-label font-weight-bold" for="id_primer_apellido">Primer apellido</label>
                                    <input type="text" name="primer_apellido" class="form-control {% if formulario.primer_apellido.errors %}is-invalid{% endif %}" id="id_primer_apellido" value="{{ formulario.primer_apellido.value }}" required>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label font-weight-bold" for="id_segundo_apellido">Segundo apellido</label>
                                    <input type="text" name="segundo_apellido" class="form-control {% if formulario.segundo_apellido.errors %}is-invalid{% endif %}" id="id_segundo_apellido" value="{{ formulario.segundo_apellido.value }}" >
                                </div>
                                
                            </div>
                            <div class="form-group col-md-6 ">
                                <label class="form-label font-weight-bold"  for="direccion_IMAGEN">Imagen</label>
                                 {{ formulario.direccion_IMAGEN }}
                                <div class="help-text">{{ formulario.direccion_IMAGEN.errors }}</div>
                            </div>
                            
                            

                            <div class="form-group col-md-6">
                                <label for="id_barrio " class="font-weight-bold">Barrio</label>
                                <select name="barrio" class="form-control {% if formulario.barrio.errors %}is-invalid{% endif %}" id="id_barrio">
                                    {% for barrio in barrios %}
                                    <option value="{{ barrio.pk }}" {% if barrio.pk == suscriptor.barrio.pk %}selected{% endif %}>{{ barrio.barrio }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label font-weight-bold" for="Estrato_socioeconomico">Estrato socioeconómico</label>
                                <div class="col-md-4">
                                  <select name="{{ formulario.Estrato_socioeconomico.name }}" class="form-control">
                                    {% for value, label in formulario.Estrato_socioeconomico.field.choices %}
                                    <option value="{{ value }}" {% if value == formulario.Estrato_socioeconomico.value %}selected{% endif %}>{{ label }}</option>
                                    {% endfor %}
                                  </select>
                                  <div class="col-12 help-text">{{ formulario.Estrato_socioeconomico.errors }}</div>
                                </div>
                              </div>
                
                              <!-- Uso -->
                              <div class="form-group">
                                <label class="col-md-4 control-label font-weight-bold" for="Uso">Uso</label>
                                <div class="col-md-4">
                                  <select name="{{ formulario.Uso.name }}" class="form-control">
                                    {% for value, label in formulario.Uso.field.choices %}
                                    <option value="{{ value }}" {% if value == formulario.Uso.value %}selected{% endif %}>{{ label }}</option>
                                    {% endfor %}
                                  </select>
                                  <div class="col-12 help-text">{{ formulario.Uso.errors }}</div>
                                </div>
                              </div>
                
                            <input type="submit" class="btn btn-primary" value="Guardar">
                        </fieldset>
                    </form>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

toma_lecturas/lecturas/templates/Suscriptor/eliminar.html
{% extends 'layout.html' %} {% block titulo %} ELIMINAR BARRIO {% endblock %} {% block section %}
<div class="card text-start">
    <div class="card-body">
        <p class="card-text">
            <h4>¿Estás seguro de que deseas eliminar este suscriptor?</h4> 
            <p>{{ barrio.barrio }}</p>

            <form method="post" action="{% url 'eliminarsuscriptor' suscriptor.id %}"> 
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a href="{% url 'indexsuscriptor' %}" class="btn btn-secondary">Cancelar</a> 
            </form>
        </p>
    </div>
</div>
{% endblock %}

toma_lecturas/lecturas/templates/Suscriptor/indexsuscriptor.html
{% extends 'layout.html' %}
{% block titulo %} INDEX SUSCRIPTORES {% endblock %}
{% block section %}
<div class="card text-start">
    <div class="card-body">
        <h4 class="card-title">Suscriptores</h4>
        <div class="d-flex justify-content-between align-items-center mb-3">
         <div class="crearbar">
          <p class="card-text">
            {% if perms.lecturas.add_suscriptor %}
                <a class="btn btn-success" href="{% url 'crearsuscriptor' %}" role="button">Registrar Suscriptor</a>
            {% endif %}
          </p>
         </div>
         <div class="barrbus">
            <div class="input-group">
                <input type="text" id="searchInputSuscriptores" placeholder="Buscar en todos los campos" class="form-control" aria-label="Buscar en todos los campos">
                <span class="input-group-text" id="basic-addon1">
                    <i class="fas fa-search"></i>
                </span>
            </div>
         </div>
        </div>
        <div class="mb-3">
            <label for="recordsPerPageSuscriptores">Mostrar</label>
            <select id="recordsPerPageSuscriptores" class="form-select w-auto d-inline">
                <option value="5">5</option>
                <option value="10" selected>10</option>
                <option value="25">25</option>
                <option value="50">50</option>
            </select>
            <label for="recordsPerPageSuscriptores">registros</label>
        </div>

        <div class="table-responsive">
            <table id="tablaSuscriptores" class="table table-striped table-borderless table-primary align-middle">
                <thead class="table-light">
                    <tr>
                        <th>Nombre Completo</th>
                        <th>Barrio</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% for suscriptor in suscriptores %}
                    <tr class="table-primary">
                        <td>{{ suscriptor.primer_nombre }} {{ suscriptor.segundo_nombre }} <br>
                            {{ suscriptor.primer_apellido }} {{ suscriptor.segundo_apellido }}
                        </td>  
                        <td>{{ suscriptor.barrio.barrio }}</td>
                        <td>
                            <a class="btn btn-outline-secondary" href="{% url 'editarsuscriptor' suscriptor.id %}" role="button">Editar</a>
                            {% if perms.lecturas.delete_suscriptor %}
                                <a id="eliminar_{{ suscriptor.id }}" class="btn btn-outline-danger" href="#" role="button">Eliminar</a>
                            {% endif %}
                            <br>
                            <a  href="{% url 'detallessuscriptor' suscriptor.id %}" role="button">Ver más detalles</a>
                        </td>
                    </tr>
                    <script>
                        document.getElementById('eliminar_{{ suscriptor.id }}').addEventListener('click', function() {
                            if (confirm('¿Estás seguro de que deseas eliminar este suscriptor?')) {
                                window.location.href = "{% url 'eliminarsuscriptor' suscriptor.id %}";
                            }
                        });
                    </script>
                    {% endfor %}
                </tbody>
                <tfoot></tfoot>
            </table>
        </div>
       <div id="paginationSuscriptores" class="mt-3 d-flex justify-content-end"></div>
    </div>
</div>

<!-- Agrega las referencias y el script de DataTables -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>

<script>
    // Inicializa la tabla con DataTables
    $(document).ready(function() {
        $('#tablaSuscriptores').DataTable();
    });
</script>
{% endblock %}